//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace J_Dimension
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mech
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Attack { get; set; }
        public Nullable<int> Defense { get; set; }
        public int Weight { get; set; }
        public string Range { get; set; }
        public string Speed { get; set; }
        public string Pilot { get; set; }
        public Nullable<int> MechGroupId { get; set; }
        public string Faction { get; set; }
    
        public virtual MechGroup MechGroup { get; set; }
    }
}
