//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace J_Dimension
{
    using System;
    using System.Collections.Generic;
    
    public partial class MechGroup
    {
        public MechGroup()
        {
            this.Mech = new HashSet<Mech>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Attack { get; set; }
        public Nullable<int> Defense { get; set; }
    
        public virtual ICollection<Mech> Mech { get; set; }
    }
}
